version: '2.1'

services:
  salt-master:
    hostname: salt-master
    container_name: salt-master
	  build:
		  - context: .
			- dockerfile: ./Dockerfile
    environment:
      - LOG_LEVEL
    ports:
      - "4505:4505"
      - "4506:4506"
    volumes:
      - ./master:/etc/salt/master
      - ./pillar/:/etc/salt/pillar/
      - ./states/:/etc/salt/states/
    command: /usr/bin/salt-master --log-file=/var/logs/salt/salt-master.log