# take a look at github pull request #16 before editing here
{% if(salt['pillar.get']('kibana:repoVersion')) %}
  {% set versionRepo = salt['pillar.get']('kibana:repoVersion') %}
  {% if versionRepo.startswith('5.') %}
{{ versionRepo }}:
  repo_url: https://artifacts.elastic.co/packages/5.x/apt
  configfile: /etc/kibana/kibana.yml
  {% endif %}
{% endif %}

{% if grains['os_family'] == 'Debian' -%}
'6':
  repo_url: https://artifacts.elastic.co/packages/6.x/apt
  configfile: /etc/kibana/kibana.yml

'5':
  repo_url: https://artifacts.elastic.co/packages/5.x/apt
  configfile: /etc/kibana/kibana.yml

'4.6':
  repo_url: http://packages.elastic.co/kibana/4.6/debian
  configfile: /etc/kibana/kibana.yml

'4.5':
  repo_url: http://packages.elastic.co/kibana/4.5/debian
  configfile: /etc/kibana/kibana.yml

{% elif grains['os_family'] == 'RedHat' -%}
'6':
  repo_url: https://artifacts.elastic.co/packages/6.x/yum
  configfile: /etc/kibana/kibana.yml

'5':
  repo_url: https://artifacts.elastic.co/packages/5.x/yum
  configfile: /etc/kibana/kibana.yml

'4.6':
  repo_url: http://packages.elastic.co/kibana/4.6/debian
  configfile: /etc/kibana/kibana.yml
'4.5':
  repo_url: http://packages.elastic.co/kibana/4.5/debian
  configfile: /etc/kibana/kibana.yml

{% endif %}